Helper Script: Add Git Installation

diff --git a/dargstack b/dargstack
--- a/dargstack
+++ b/dargstack
@@ -17,6 +17,29 @@ LIGHT_RED='\e[91m'
 LIGHT_YELLOW='\e[93m'
 NC='\e[0m'
 
+if [ "$(which git > /dev/null)" == "" ]
+then
+	echo -e "${LIGHT_BLUE}git${LIGHT_YELLOW} is not available.${NC}"
+
+	if [ "$(which lsb_release > /dev/null)" == "" ]
+	then
+		echo -e "${LIGHT_RED}Could not determine OS distribution!${NC}"
+		echo -e "${LIGHT_BLUE}lsb_release${NC} is not available."
+		exit 1
+	fi
+
+	if [[ ("$(lsb_release -is)" == "Debian")
+		|| ("$(lsb_release -is)" == "Ubuntu") ]]
+	then
+		sudo apt-get install -y git
+	else
+		echo -e "${LIGHT_RED}Could not install ${LIGHT_BLUE}git${LIGHT_RED}" \
+			" automatically!${NC}"
+		echo -e "Please install it manually."
+		exit 1
+	fi
+fi
+
 # Get this script's directory
 THIS=$(dirname $(readlink -f "$0"))
 
